# Generated by Django 5.1.5 on 2025-03-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('todo', 'ToDo'), ('inprogress', 'In Progress'), ('done', 'Done')], default='todo', max_length=50)),
            ],
        ),
    ]
